value:
  maximum_name: 50
  maximum_email: 50
  start_date: 10
  end_date: 100
  user_page: 20
  product_page: 20
  minimum_price: 1
  maximum_price: 10000
  minimum_password: 6
  maximum_password: 15
